"""Add missing artifact columns

Revision ID: 75e697ec1214
Revises: 0004_feedback_enforcement
Create Date: 2026-09-18 21:25:53.142023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '75e697ec1214'
down_revision: Union[str, None] = '0004_feedback_enforcement'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingestion_source', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('provider_message_id', sa.String(length=512), nullable=True))

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'investigations', ['investigation_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['actor_user_id'], ['id'])

    with op.batch_alter_table('score_conclusions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verdict', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('one_line_explanation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('why_explanation', sa.Text(), nullable=True))
        batch_op.alter_column('category_breakdown',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_conclusions', schema=None) as batch_op:
        batch_op.alter_column('category_breakdown',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.drop_column('why_explanation')
        batch_op.drop_column('one_line_explanation')
        batch_op.drop_column('verdict')

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_column('provider_message_id')
        batch_op.drop_column('ingestion_source')

    # ### end Alembic commands ###
