"""add_artifact_id_to_analysis_run

Revision ID: b23a90c6e0dd
Revises: 75e697ec1214
Create Date: 2026-09-19 16:40:17.082698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b23a90c6e0dd'
down_revision: Union[str, None] = '75e697ec1214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add nullable column
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artifact_id', sa.String(length=36), nullable=True))
        
    # 2. Backfill artifact_id from artifacts
    op.execute(
        """
        UPDATE analysis_runs 
        SET artifact_id = (
            SELECT id FROM artifacts 
            WHERE artifacts.investigation_id = analysis_runs.investigation_id 
            ORDER BY created_at ASC LIMIT 1
        )
        """
    )

    # 3. Make it non-nullable and add FK
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.alter_column('artifact_id', nullable=False)
        batch_op.create_foreign_key('fk_analysis_runs_artifact_id', 'artifacts', ['artifact_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('artifact_id')

    # ### end Alembic commands ###
