"""add mitre_id to findings

Revision ID: e3f9a72b0c45
Revises: b23a90c6e0dd
Create Date: 2026-09-25 19:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f9a72b0c45'
down_revision: Union[str, None] = 'b23a90c6e0dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mitre_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_column('mitre_id')
    # ### end Alembic commands ###
